project:
  type: website
  output-dir: docs

website:
  title: "Colby's Website"
  site-url: "https://colbysp.github.io/"
  favicon: favicon.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ColbySP
      - icon: linkedin
        href: https://www.linkedin.com/in/colbysp/
  google-analytics:
    tracking-id: "G-8VGP46KHDR"
    storage: none

format:
  html:
    theme: flatly
    css: styles.css



