project:
  type: website
  output-dir: docs

website:
  title: "Colby's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ColbySP
      - icon: linkedin
        href: https://www.linkedin.com/in/colbysp/
format:
  html:
    theme: cosmo
    css: styles.css



